apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
data:
  default.conf: |
    server {
      listen {{ .Values.port }};
      server_name {{ .Values.domainName }};
      root /usr/share/nginx/html;
      index index.html;

      location / {
        try_files $uri /index.html;
      }
    }
